name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is available

      - name: Run Tests
        run: pytest tests/

  docker_build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t sentiment-analyzer:latest .

      # Optionally, you can add steps to push the image to a container registry
      # Uncomment and configure if needed:
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Push Docker Image
      #   run: |
      #     docker tag sentiment-analyzer:latest ${{ secrets.DOCKER_USERNAME }}/sentiment-analyzer:latest
      #     docker push ${{ secrets.DOCKER_USERNAME }}/sentiment-analyzer:latest
